#!/bin/bash
# Kid tested, mother approved
# vano@51.ru

#   if not find soapysdr when build SoapyUHD 
#   sudo add-apt-repository -y ppa:myriadrf/drivers
#   sudo apt-get install libsoapysdr-dev
#   sudo apt-get update
# who am i?
id=`id -u`
if [ $id -ne 0 ]; then
   echo it is more convenient to install all this as root
   echo either run this script as sudo ./scriptname or
   echo become root and run it.
   echo press control-c to abort, or press enter to continue
   echo if you continue, expect to enter your password a bunch
   echo of times
fi

read -p "Installing dependencies"
sudo apt-get install -y git g++ cmake libsqlite3-dev  libi2c-dev libusb-1.0-0-dev libwxgtk3.0-dev freeglut3-dev libboost-all-dev swig liblog4cpp5-dev build-essential libtool libtalloc-dev shtool autoconf automake git-core pkg-config make gcc libpcsclite-dev gnutls-bin gnutls-dev python

read -p "Installing LimeSuite"
echo Installing LimeSuite
rm -r LimeSuite
git clone https://github.com/myriadrf/LimeSuite.git
cd LimeSuite
mkdir builddir && cd builddir
cmake ../
make -j4
sudo make install
sudo ldconfig
cd ~
cd LimeSuite/udev-rules
chmod 777 ./install.sh
sudo ./install.sh

read -p "Installing libosmocore"
cd ~
rm -r libosmocore
git clone git://git.osmocom.org/libosmocore
cd libosmocore
autoreconf -fi
./configure
make
sudo make install
sudo ldconfig
cd ../

read -p "Installing osmo-trx"
cd ~
rm -r osmo-trx
git clone git://git.osmocom.org/osmo-trx
cd osmo-trx
autoreconf -fi
./configure --without-uhd --with-lms
make
sudo make install
sudo ldconfig

read -p "Connect Limesdr within 20 seconds and press Enter"
#leep 20

#now run LimeUtil with --find to locate devices on the system
LimeUtil --find

read -p "Installing osmocom-nitb osmo-bts-trx"
cd ~
wget http://download.opensuse.org/repositories/network:/osmocom:/latest/Debian_9.0/Release.key 
sha256sum Release.key
apt-key add Release.key
rm Release.key
chmod 777 /etc/apt/sources.list.d/osmocom-latest.list
echo "deb http://download.opensuse.org/repositories/network:/osmocom:/latest/Debian_9.0/ ./" > /etc/apt/sources.list.d/osmocom-latest.list
apt-get update

apt-get install osmocom-nitb osmo-bts-trx

cd ~
mkdir configs && cd configs
touch openbsc.cfg
touch osmo-bts.cfg
touch osmo-trx.cfg

echo "!
! OpenBSC configuration saved from vty
!   !
password foo
!
line vty
no login
!
e1_input
e1_line 0 driver ipa
network
network country code 313
mobile network code 37
short name Codeby
long name Codeby
auth policy accept-all
location updating reject cause 13
encryption a5 0
neci 1
rrlp mode none
mm info 1
handover 0
handover window rxlev averaging 10
handover window rxqual averaging 1
handover window rxlev neighbor averaging 10
handover power budget interval 6
handover power budget hysteresis 3
handover maximum distance 9999
bts 0
  type sysmobts
  band GSM900
  cell_identity 0
  location_area_code 1
  training_sequence_code 7
  base_station_id_code 63
  ms max power 15
  cell reselection hysteresis 4
  rxlev access min 0
  channel allocator ascending
  rach tx integer 9
  rach max transmission 7
  ip.access unit_id 1801 0
  oml ip.access stream_id 255 line 0
  gprs mode none
  trx 0
   rf_locked 0
   arfcn 100
   nominal power 23
   max_power_red 20
   rsl e1 tei 0
   timeslot 0
    phys_chan_config CCCH+SDCCH4
   timeslot 1
    phys_chan_config SDCCH8
   timeslot 2
    phys_chan_config TCH/F
   timeslot 3
    phys_chan_config TCH/F
   timeslot 4
    phys_chan_config TCH/F
   timeslot 5
    phys_chan_config TCH/F
   timeslot 6
    phys_chan_config TCH/F
   timeslot 7
    phys_chan_config TCH/F" > /root/configs/openbsc.cfg

echo "!
! OsmoBTS configuration example
!!
!
log stderr
  logging color 1
  logging timestamp 0
  logging level rsl notice
  logging level oml notice
  logging level rll notice
  logging level rr notice
  logging level loop debug
  logging level meas debug
  logging level pag error
  logging level l1c error
  logging level l1p error
  logging level dsp error
  logging level abis error
!
line vty
no login
!
phy 0
instance 0
  osmotrx rx-gain 40
  osmotrx tx-attenuation 50
osmotrx ip local 127.0.0.1
osmotrx ip remote 127.0.0.1
no osmotrx timing-advance-loop
bts 0
oml remote-ip 127.0.0.1
ipa unit-id 1801 0
gsmtap-sapi pdtch
gsmtap-sapi ccch
band 900
trx 0
  phy 0 instance 0" > /root/configs/osmo-bts.cfg

echo "log stderr
logging filter all 1
logging color 1
logging print category 1
logging timestamp 1
logging print file basename
logging level set-all info
!
line vty
no login
!
trx
bind-ip 127.0.0.1
remote-ip 127.0.0.1
base-port 5700
egprs disable
tx-sps 4
rx-sps 4
rt-prio 18
chan 0
  tx-path BAND1
  rx-path LNAW" > /root/configs/osmo-trx.cfg

cd ~
touch start_bts.sh
echo "#!/bin/sh
sysctl -w kernel.sched_rt_runtime_us=-1
cd /root/configs
osmo-nitb &
NITB=$!
chrt -rr 99 osmo-trx-lms &
TRX=$!
sleep 5
osmo-bts-trx &
BTS=$!
wait $NITB $BTS $TRX" > /root/start_bts.sh
chmod +x start_bts.sh
